#+TITLE: Spacemacs configuration

* Mac OSX 

#+begin_src emacs-lisp
(setq default-input-method "MacOSX")
(setq mac-command-modifier 'meta)
(setq mac-option-modifier 'none)
#+end_src

* Capture templates

* Easy templates

* Package configuration

** Deft

#+begin_quote
Deft is an Emacs mode for quickly browsing, filtering, and editing directories of plain text notes, inspired by Notational Velocity. It was designed for increased productivity when writing and taking notes by making it fast and simple to find the right file at the right time and by automating many of the usual tasks such as creating new files and saving files.
#+end_quote

#+begin_src emacs-lisp
(setq deft-directory "~/org/notes/")
(setq deft-file-naming-rules
  '((noslash . "-")
  (nospace . "-")
  (case-fn . downcase)))
(setq deft-use-filename-as-title nil)
(setq deft-org-mode-title-prefix t)
#+end_src

** org-mode

*** Fix "M-RET broken in org-mode" 

    Fix for binding M-RET to org-meta-return instead of acting as major mode leader key.
    See [[https://github.com/syl20bnr/spacemacs/issues/9603#issuecomment-435283494]] for more infos.

#+begin_src emacs-lisp
(with-eval-after-load 'org 
  (org-defkey org-mode-map [(meta return)] 'org-meta-return)
)
#+end_src

** org-contacts 

#+begin_src emacs-lisp
(use-package org-contacts
  :ensure nil
  :after org
  :custom (org-contacts-files '("~/org/contacts.org")))
#+end_src

* Load =.custom.el=

  Copied from [[https://github.com/angrybacon/dotemacs/blob/master/dotemacs.org]].

#+begin_quote
One is able to use the customization interface that is bundled within Emacs. It
is meant to help people who are not familiar with Emacs Lisp in the
configuration of Emacs itself. By default, changes in the customization will be
automatically detected and appended at the end of the configuration file,
=init.el=.

Since that in my case, the actual configuration file is a new one, crafted by
=org-mode=, adding code at the end of =init.el= might mess things up. The
following tells Emacs to add extra code in another file that would be then
loaded, if existing.
#+end_quote

#+BEGIN_SRC emacs-lisp
(setq-default custom-file (expand-file-name ".custom.el" user-emacs-directory))
(when (file-exists-p custom-file)
  (load custom-file))
#+END_SRC
